[build]
builder = "nixpacks"
watchPatterns = ["**"]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --limit-request-line 0 --limit-request-field_size 0"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
